version: "3"

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.20.0
    volumes:
      - ./prometheus/prometheus.yml:/prometheus/prometheus.yml
    command:
      - '--config.file=/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - 9090:9090


  grafana:
    container_name: grafana
    image: grafana/grafana:7.1.0
    volumes:
      - ./grafana/grafana.ini:/grafana/grafana.ini
      - ./grafana/datasources.yml:/grafana/provisioning/datasources/datasources.yml
      - ./grafana/dashboards.yml:/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/dashboards:/grafana/provisioning/dashboards/dashboards
    ports:
      - 3000:3000

